import { Check, Circle, Link2, Pencil, Rows3 } from "lucide-react";
import Link from "next/link";

import { linkedRecordLabels } from "@/features/data-workspace/materialize";
import type { DataFieldDefinition, MaterializedRecord, MaterializedValue } from "@/features/data-workspace/types";
import { formatCurrency, formatProjectDate } from "@/lib/format";

function DisplayValue({ field, value, recordMap, currencyCode }: { field: DataFieldDefinition; value: MaterializedValue; recordMap: Map<string, MaterializedRecord>; currencyCode: string }) {
  if (value === null || value === "" || (Array.isArray(value) && value.length === 0)) return <span className="text-slate-300">—</span>;
  if (field.field_type === "checkbox") return value === true ? <span className="inline-flex items-center gap-1.5 font-semibold text-green-700"><Check className="size-4" aria-hidden="true" />Checked</span> : <span className="inline-flex items-center gap-1.5 text-slate-500"><Circle className="size-3" aria-hidden="true" />Not checked</span>;
  if (field.field_type === "currency" && typeof value === "string") return <span className="font-semibold tabular-nums">{formatCurrency(Number(value), currencyCode)}</span>;
  if (field.field_type === "date" && typeof value === "string") return formatProjectDate(value);
  if (field.field_type === "link") {
    const labels = linkedRecordLabels(value, recordMap);
    return <span className="flex flex-wrap gap-1">{labels.map((label, index) => <span className="inline-flex items-center gap-1 rounded-md bg-violet-100 px-2 py-1 text-xs font-bold text-violet-900" key={`${label}-${index}`}><Link2 className="size-3" aria-hidden="true" />{label}</span>)}</span>;
  }
  if (Array.isArray(value)) return <span className="flex flex-wrap gap-1">{value.map((item, index) => <span className="rounded-md bg-slate-100 px-2 py-1 text-xs font-semibold text-slate-700" key={`${item}-${index}`}>{item}</span>)}</span>;
  return <span className={field.field_type === "number" || field.field_type === "formula" ? "tabular-nums" : ""}>{String(value)}</span>;
}

function compactValue(value: MaterializedValue | undefined) {
  if (Array.isArray(value)) return value.join(", ");
  return value === null || value === undefined ? "—" : String(value);
}

export function DataGrid({ fields, records, allRecords, tableId, currencyCode, viewType }: { fields: DataFieldDefinition[]; records: MaterializedRecord[]; allRecords: MaterializedRecord[]; tableId: string; currencyCode: string; viewType: string }) {
  const recordMap = new Map(allRecords.map((record) => [record.id, record]));
  if (!records.length) return <div className="grid min-h-[360px] place-items-center bg-white p-8 text-center"><div><span className="mx-auto grid size-12 place-items-center rounded-xl bg-slate-100 text-slate-600"><Rows3 className="size-6" aria-hidden="true" /></span><h2 className="mt-4 font-extrabold text-slate-900">No records in this view</h2><p className="mt-1 max-w-sm text-sm leading-6 text-slate-500">Use New record to add the first row. Required fields and linked-record rules will be checked when it is saved.</p></div></div>;

  if (viewType === "gallery") return <div className="grid gap-4 bg-slate-50 p-4 sm:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4">{records.map((record) => <article className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm" key={record.id}><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[0.12em] text-slate-500">Record {record.record_number}</p><h2 className="mt-1 font-extrabold text-slate-950">{record.label}</h2></div><Link aria-label={`Edit ${record.label}`} className="grid size-11 place-items-center rounded-lg text-slate-500 hover:bg-slate-100 focus-visible:outline-none focus-visible:ring-3 focus-visible:ring-blue-700/25" href={`/data/${tableId}?panel=record&record=${record.id}`}><Pencil className="size-4" /></Link></div><dl className="mt-4 grid gap-3">{fields.filter((field) => !field.is_primary).slice(0, 5).map((field) => <div key={field.id}><dt className="text-xs font-bold text-slate-500">{field.name}</dt><dd className="mt-1 text-sm text-slate-800"><DisplayValue currencyCode={currencyCode} field={field} recordMap={recordMap} value={record.values[field.id] ?? null} /></dd></div>)}</dl></article>)}</div>;

  if (viewType === "list") return <ul className="divide-y divide-slate-200 bg-white">{records.map((record) => <li className="flex items-center gap-4 px-4 py-3" key={record.id}><span className="w-10 shrink-0 text-right text-xs font-semibold tabular-nums text-slate-400">{record.record_number}</span><div className="min-w-0 flex-1"><p className="truncate font-bold text-slate-900">{record.label}</p><p className="mt-1 truncate text-xs text-slate-500">{fields.filter((field) => !field.is_primary).slice(0, 3).map((field) => `${field.name}: ${compactValue(record.values[field.id])}`).join(" · ")}</p></div><Link className="inline-flex min-h-11 items-center gap-2 rounded-lg px-3 text-sm font-bold text-blue-800 hover:bg-blue-50 focus-visible:outline-none focus-visible:ring-3 focus-visible:ring-blue-700/25" href={`/data/${tableId}?panel=record&record=${record.id}`}><Pencil className="size-4" aria-hidden="true" />Edit</Link></li>)}</ul>;

  return <>
    <div className="hidden overflow-x-auto bg-white md:block" role="region" aria-label="Records grid" tabIndex={0}><table className="min-w-max border-collapse text-left text-sm"><thead className="sticky top-0 z-10 bg-slate-100"><tr><th className="w-14 border-b border-r border-slate-300 px-3 py-2 text-right text-xs font-bold text-slate-500">#</th>{fields.map((field) => <th className="min-w-52 border-b border-r border-slate-300 px-3 py-2 font-bold text-slate-800" key={field.id}><span className="flex items-center gap-2"><span className="truncate">{field.name}</span><span className="ml-auto text-[10px] font-semibold uppercase tracking-wide text-slate-400">{field.field_type.replaceAll("_", " ")}</span></span></th>)}<th className="w-20 border-b border-slate-300 px-3 py-2"><span className="sr-only">Actions</span></th></tr></thead><tbody>{records.map((record) => <tr className="group hover:bg-blue-50/50" key={record.id}><td className="border-b border-r border-slate-200 px-3 py-2 text-right text-xs font-semibold tabular-nums text-slate-400">{record.record_number}</td>{fields.map((field) => <td className="max-w-sm border-b border-r border-slate-200 px-3 py-2 align-top text-slate-800" key={field.id}><DisplayValue currencyCode={currencyCode} field={field} recordMap={recordMap} value={record.values[field.id] ?? null} /></td>)}<td className="border-b border-slate-200 px-2 py-1"><Link aria-label={`Edit ${record.label}`} className="grid size-10 place-items-center rounded-lg text-slate-400 opacity-70 hover:bg-white hover:text-blue-800 focus-visible:opacity-100 focus-visible:outline-none focus-visible:ring-3 focus-visible:ring-blue-700/25 group-hover:opacity-100" href={`/data/${tableId}?panel=record&record=${record.id}`}><Pencil className="size-4" /></Link></td></tr>)}</tbody></table></div>
    <div className="grid gap-3 bg-slate-50 p-3 md:hidden">{records.map((record) => <article className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm" key={record.id}><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-bold text-slate-400">#{record.record_number}</p><h2 className="mt-1 font-extrabold text-slate-950">{record.label}</h2></div><Link className="inline-flex min-h-11 items-center gap-2 rounded-lg px-3 text-sm font-bold text-blue-800 hover:bg-blue-50" href={`/data/${tableId}?panel=record&record=${record.id}`}><Pencil className="size-4" aria-hidden="true" />Edit</Link></div><dl className="mt-4 grid gap-3">{fields.filter((field) => !field.is_primary).map((field) => <div className="grid grid-cols-[minmax(0,0.8fr)_minmax(0,1.2fr)] gap-3" key={field.id}><dt className="text-xs font-bold text-slate-500">{field.name}</dt><dd className="min-w-0 text-sm text-slate-800"><DisplayValue currencyCode={currencyCode} field={field} recordMap={recordMap} value={record.values[field.id] ?? null} /></dd></div>)}</dl></article>)}</div>
  </>;
}
